### ISSUE TITLE
Use decorator for authentication

### ISSUE THREAD

**Issue by bonnetn** [HackademINT/Proxmox-Security-Integration-Tool#1]
https://github.com/HackademINT/Proxmox-Security-Integration-Tool/blob/9fa2bff969967c34d6e4c938facf3d9d73709879/web/main.py#L21

Instead of writing if-clauses at the beginning of each function, you can create a decorator that you would apply to every endpoint that requires authentication.

**Comment by zteeed** [comment]
Done with commit 37cdcc58188b902889092ff3675cfe93bf8cb9c6
