### ISSUE TITLE
Use Passlib to store passwords

### ISSUE THREAD

**Issue by bonnetn** [HackademINT/Proxmox-Security-Integration-Tool#2]
https://github.com/HackademINT/Proxmox-Security-Integration-Tool/blob/9fa2bff969967c34d6e4c938facf3d9d73709879/web/config.py#L88

You can use the passlib library to hash password safely.

https://passlib.readthedocs.io/en/stable/

**Comment by bonnetn** [comment]
I think, using a [CryptContext](https://passlib.readthedocs.io/en/stable/narr/quickstart.html#creating-and-using-a-cryptcontext) would be relevant here.

**Comment by zteeed** [comment]
TODO: 
- Use https://pythonhosted.org/flask-mail/ to generate random passwords for new user (update Users class)
- Store the hash with CryptContext in database

**Comment by zteeed** [comment]
Done with commit e6410aab957abede0994d37f3adcabdc79f4c539
